version: '3'

services:
  mongodb:
    image: postgres:latest
    restart: always
    container_name: "postgres-container"
    hostname: postgres-host
    environment:
      - POSTGRES_PASSWORD=techbankRootPsw
    ports:
      - "5433:5432"
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
   
networks:
  default:
    external:
      name: techbankNet