version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongo-container"
    hostname: mongodb-host
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data_container:/data/db
   
networks:
  default:
    external:
      name: techbankNet